{
  username,
  ...
}:
{
  home-manager.users.${username} = {
    xdg.configFile."monitors.xml".force = true;
    xdg.configFile."monitors.xml".text = ''
      <monitors version="2">
        <configuration>
          <layoutmode>logical</layoutmode>
          <logicalmonitor>
            <x>1440</x>
            <y>629</y>
            <scale>1</scale>
            <primary>yes</primary>
            <monitor>
              <monitorspec>
                <connector>DP-10</connector>
                <vendor>AUS</vendor>
                <product>VG27A</product>
                <serial>M5LMQS167257</serial>
              </monitorspec>
              <mode>
                <width>2560</width>
                <height>1440</height>
                <rate>144.006</rate>
              </mode>
            </monitor>
          </logicalmonitor>
          <logicalmonitor>
            <x>0</x>
            <y>0</y>
            <scale>1</scale>
            <transform>
              <rotation>left</rotation>
              <flipped>no</flipped>
            </transform>
            <monitor>
              <monitorspec>
                <connector>DP-8</connector>
                <vendor>AUS</vendor>
                <product>VG27A</product>
                <serial>M5LMQS167247</serial>
              </monitorspec>
              <mode>
                <width>2560</width>
                <height>1440</height>
                <rate>59.951</rate>
              </mode>
            </monitor>
          </logicalmonitor>
        </configuration>
      </monitors>
    '';
  };
}
