name: "NixOS Configuration Style Check"

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  style-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Check Nix flake inputs
      run: nix flake check
    - name: Run statix
      run: nix run nixpkgs#statix -- check .
    - name: Run deadnix
      run: nix run nixpkgs#deadnix -- -f .
    - name: Run nixfmt-rfc-style
      run: |
        nix run nixpkgs#nixfmt-rfc-style -- --check .
    - name: Run nixpkgs-lint
      run: nix run nixpkgs#nixpkgs-lint-community -- .
    - name: Validate flake.nix
      run: nix flake show
